"""empty message

Revision ID: 8955f6a86dc2
Revises: 16ddbd8f62f0
Create Date: 2021-09-25 17:02:45.501236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8955f6a86dc2'
down_revision = '16ddbd8f62f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marvel_character', 'comics_appeared_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel_character', sa.Column('comics_appeared_in', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
