"""empty message

Revision ID: 8d86d931c0e0
Revises: 8955f6a86dc2
Create Date: 2021-09-25 17:03:07.610349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d86d931c0e0'
down_revision = '8955f6a86dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel_character', sa.Column('comics_appeared_in', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marvel_character', 'comics_appeared_in')
    # ### end Alembic commands ###
